-- Sa se creeze tabelele si legaturile dintre acestea conform modelului specificat
-- Sa se adauge cate 5 intrari in fiecare tabela 
-- Sa se afiseze toate intrarile din fiecare tabela
-- Sa se afiseze toate persoanele de un anumit sex
-- Sa se afiseze toti angajatii din departamentul cu id-ul 3
-- Nume ang - dept 3
-- Sa se actualizeze la alegere o intrare din orice tabela
-- Sa se stearga o intrare din tabela SAL_GRADE
-- DELETE FROM SAL_GRADE WHERE ID=5;
-- Sa se stearga tabela SAL_GRADE
-- Sa se refaca tabela SAL_GRADE (copiati ce ati scris anterior)
-- Sa se gaseasca toti angajatii de sex feminin
-- Sa se gaseasca angajatii din departamentul cu numele 'IT'
-- Sa se gaseasca id-urile tuturor studentilor care sunt si angajati
-- Sa se gaseasca id-urile tuturor studentilor care sunt angajati in departamentul 'IT'
-- Sa se gaseasca numarul total de persoane
-- Sa se afiseze gradul salarial, valorile acestuia si salariul total  pentru fiecare angajat, luand in calcul si comisionul ordonati crescator dupa EMP_ID
-- Gradul salarial al studentiilor din 'ACS'
